name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * TUE"
  workflow_dispatch:

jobs:
  test-packages-in-docker:
    strategy:
      matrix:
        tag-name: [debian-12, debian-testing, debian-unstable, debian-experimental]
      fail-fast: false
    container: ghcr.io/dmf-unicatt/latex-packages:latest-${{ matrix.tag-name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show texlive version
        run: dpkg -s texlive-base | grep Version
      - name: Ensure that \LaTeXTwentyFivefalse at the end of packages/if-latex-twentyfive.sty is always commented when committing
        run: git-hooks/pre-commit
      - name: Run unit tests
        run: |
          cd tests
          python run_tests.py unit

  test-packages-in-act:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install act
        run: |
          curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
      - name: Setup act config
        run: |
          echo "-P ubuntu-latest=medium" > .actrc
      - name: Run tests under act
        run: |
          export PATH=$PWD/bin:$PATH
          cd tests
          bash run_tests_act.sh
